spring:
  cloud:
    nacos:
      discovery:
        server-addr: 112.124.12.211:8848
  application:
    name: lyf--auth-service

  redis:
    host: 192.168.230.129
    port: 6379

server:
  port: 20000